Documentation:
  Enabled: false

Rails:
  Enabled: true

# Rails 5 feature
Rails/ApplicationRecord:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
