# development:
#   google_client_id: ...
#   google_client_secret: ...

# test:
#   google_client_id: ...
#   google_client_secret: ...

# production:
#   google_client_id: ...
#   google_client_secret: ...