development:
  google_client_id: "764296591688-srfkad2uvh0rbseqlakjj608irm1erdo.apps.googleusercontent.com"
  google_client_secret: "VBfK6kGrY0hNeOF_AbC8Lj41"

test:
  google_client_id: "764296591688-srfkad2uvh0rbseqlakjj608irm1erdo.apps.googleusercontent.com"
  google_client_secret: "VBfK6kGrY0hNeOF_AbC8Lj41"

production:
  google_client_id: "764296591688-oj8b3pc2q27tmvjoirlo1d2q0ppj6shi.apps.googleusercontent.com"
  google_client_secret: "6-uryhlPJQeb7EpPuMzNb_Ar"