development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ifme_development
  allow_concurrency: true
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ifme_test
  allow_concurrency: true
  pool: 5
  min_messages: error

production:
  adapter: postgresql
  encoding: unicode
  database: ifme_production
  allow_concurrency: true
  pool: 5
