development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: ifme_development
  allow_concurrency: true
  pool: 5
  min_messages: warning
  username: <%= ENV["PSQL_USERNAME"] %>
  password: <%= ENV["PSQL_PASSWORD"] %>

test:
  <<: *default
  database: ifme_test
  min_messages: error

production:
  adapter: postgresql
  encoding: unicode
  database: ifme_production
  allow_concurrency: true
  pool: 5
