# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 685413ce3f604f2c7aa089e4caa6ff6767fa7592c08cbaedf25b2046dca3fdb26e3ea4c095860035908c79286869bdbf49a6ace56633c90610e00c14eba9f18b

test:
  secret_key_base: eeec52c51223588138405f240bb6106ac936028579a73dcba7bc0847a1c637e5d5faf38ad988aca92cf51ab81285a04fac62f5604886d338e704a659a9d4f491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
